spring.application.name=Quiz

spring.datasource.url=jdbc:postgresql://dpg-d81f7ot7vvec73f1tk90-a/quizdb_5hcw

spring.datasource.username=quizdb_5hcw_user

spring.datasource.password=W2RaThQROQEdG5jjNU030RTZYhQOWvdG

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true

spring.jpa.defer-datasource-initialization=true

server.port=${PORT:8080}