insert into question
(topic,question,option1,option2,option3,option4,answer)
values
('Java',
'Which keyword is used for inheritance?',
'implement',
'extends',
'inherits',
'super',
'extends'),

('Java',
'Which collection allows duplicate values?',
'Set',
'Map',
'List',
'TreeSet',
'List'),

('Java',
'Which method is the entry point of Java program?',
'run()',
'start()',
'main()',
'init()',
'main()'),

('Java',
'Which package contains ArrayList class?',
'java.io',
'java.lang',
'java.sql',
'java.util',
'java.util'),
('SQL',
'Which clause is used to filter rows?',
'ORDER BY',
'GROUP BY',
'WHERE',
'HAVING',
'WHERE'),

('SQL',
'Which command removes all rows from a table?',
'DELETE',
'DROP',
'REMOVE',
'TRUNCATE',
'TRUNCATE'),

('SQL',
'Which JOIN returns matching rows from both tables?',
'LEFT JOIN',
'RIGHT JOIN',
'INNER JOIN',
'FULL JOIN',
'INNER JOIN'),

('SQL',
'Which aggregate function counts rows?',
'COUNT()',
'SUM()',
'TOTAL()',
'NUMBER()',
'COUNT()'),
('JavaScript',
'Which keyword declares a variable?',
'int',
'String',
'var',
'define',
'var'),

('JavaScript',
'Which symbol is used for comments in JavaScript?',
'<!-- -->',
'//',
'**',
'##',
'//'),

('JavaScript',
'Which method prints output in console?',
'console.log()',
'print()',
'echo()',
'write()',
'console.log()'),

('JavaScript',
'Which keyword is used for constant variables?',
'let',
'static',
'final',
'const',
'const');